services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env # Load environment variables from .env file
    environment:
      - NODE_ENV=development
      - COUCHDB_URL=http://admin:securepassword123@next-couchdb:5984
      - COUCHDB_DB=next_database
    volumes:
      - ./:/app
      - /app/node_modules
      - pnpm-store:/pnpm/store
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - next_network
  couchdb:
    container_name: next-couchdb
    image: couchdb:3.4.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=securepassword123
    ports:
      - '5984:5984'
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: always
    networks:
      - next_network

networks:
  next_network:
    driver: bridge

volumes:
  couchdb_data:
  pnpm-store: # survives container rebuilds and code changes
