services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
      - pnpm-store:/pnpm/store # ← persistent global pnpm store (fast & stable)
    restart: unless-stopped
    ports:
      - '3000:3000'
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - node_modules/
    #         - .next/
    #     - action: rebuild
    #       path: package.json
    networks:
      - next_network

  couchdb:
    container_name: next-couchdb
    image: couchdb:3.4.2
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=securepassword123
    ports:
      - '5984:5984'
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: always
    networks:
      - next_network

networks:
  next_network:
    driver: bridge

volumes:
  couchdb_data:
  pnpm-store: # survives container rebuilds and code changes
